
CREATE TABLE registry.ddm_liquibase_metadata (
    metadata_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    change_type TEXT NOT NULL,
    change_name TEXT NOT NULL,
    attribute_name TEXT NOT NULL,
    attribute_value TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_ddm_liquibase_metadata PRIMARY KEY (metadata_id)
);
